- hosts: ["tag_Name_K8S_Master"]
  roles:
  - name: "Configuring Master Node"
    role:  "/k8s-multi-node-cluster/k8s-master"

- hosts: ["tag_Name_K8S_Slave1", "tag_Name_K8S_Slave2"]
  vars_prompt:
  - name: "master_token"
    prompt: "Enter Token to Join Slaves to Master: "
    private: no
  roles:
  - name: "Configuring Slave Nodes"
    role:  "/k8s-multi-node-cluster/k8s-slaves"
