---
# tasks file for k8s-slaves

 - name: "Installing docker"
   package:
     name: docker
     state: present

 - name: "Starting and Enabling docker service"
   service:
     name: docker
     state: started
     enabled: yes

 - name: "Configuring yum repo for kubernetes"
   copy:
     src: "/k8s-multi-node-cluster/k8s-slaves/files/kubernetes.repo"
     dest: "/etc/yum.repos.d/kubernetes.repo"

 - name: "Installing kubeadm, kubectl, kubelet"
   yum:
     name: "{{ item }}"
     state: present
     disable_excludes: kubernetes
   loop: "{{ packages }}"

 - name: "Starting and Enabling kubelet"
   service:
     name: kubelet
     state: started
     enabled: yes

 - name: "Changing the driver in the docker"
   copy:
      content: |
         {
            "exec-opts": ["native.cgroupdriver=systemd"]
         }
      dest: /etc/docker/daemon.json
   register: output

 - name: "Restarting Docker"
   service:
      name: docker
      state: restarted
   when: output.changed == true

 - name: "Installing iproute-tc"
   package:
      name: iproute-tc
      state: present

 - name: "Setting bridge-nf-call-iptables to 1"
   shell: | 
       echo "1"  > /proc/sys/net/bridge/bridge-nf-call-iptables
       echo "1"  > /proc/sys/net/bridge/bridge-nf-call-ip6tables
   changed_when: false   

 - name: "Joining Slave to Master"
   shell: "{{ master_token }}"
   ignore_errors: yes
   register: joined

 - debug:
     var: joined.stdout_lines

    
